feat: add pagination component
SigNoz/components pull request #20
Opened 2024-10-13 11:42 UTC by ahmadshaheer

2024-10-28 08:27 UTC, YounixM commented on apps/docs/stories/pagination.stories.tsx
> +  <Pagination>
Check https://ant.design/components/pagination for examples

2024-10-28 08:28 UTC, YounixM commented
@ahmadshaheer : the story should list all the props the component accepts.

2024-10-29 15:29 UTC, ahmadshaheer commented on apps/docs/stories/pagination.stories.tsx
> +  <Pagination>
Done :+1:

2025-03-26 06:28 UTC, GeekBoySupreme requested changes
- Are we using Lucide icons here for the chevrons? Idk why the strokes looked very thin and similar to Ant-D icons for me 🤔
- Border radius needs to be reduced. Please cross-check with the design.

2025-04-25 17:41 UTC, ahmadshaheer commented
closing in favor of #50, @GeekBoySupreme, I have addressed your comments there.

2025-04-25 17:41 UTC, closed without merging